export enum Permissions {
    // USERS -> PERMISSIONS
    READ_USERS = 'READ_USERS',
    DELETE_USERS = 'DELETE_USERS',

    // ADMININSTRATIVE TEAM -> PERMISSIONS
    CREATE_TEAM = 'CREATE_TEAM',
    DELETE_TEAM = 'DELETE_TEAM',
    UPDATE_TEAM = 'UPDATE_TEAM',
    READ_TEAM = 'READ_TEAM',
    BAN_TEAM = 'BAN_TEAM',

    // FAQ CATEGORY -> PERMISSIONS
    CREATE_FAQ_CATEGORY = 'CREATE_FAQ_CATEGORY',
    DELETE_FAQ_CATEGORY = 'DELETE_FAQ_CATEGORY',
    UPDATE_FAQ_CATEGORY = 'UPDATE_FAQ_CATEGORY',
    READ_FAQ_CATEGORY = 'READ_FAQ_CATEGORY',
}